import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import Header from "../components/layout/Header";
import { getCurrentSession } from "@/actions/auth";
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "@/components/layout/HeaderCategorySelector";
import Cart from "@/components/cart/Cart";
import Script from "next/script";
import { Suspense } from "react";
import AnalyticsTracker from "@/components/layout/AnalytcsTracker";

const inter = Inter({ subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({children}:Readonly<{children:React.ReactNode}>) => {
  const {user} = await getCurrentSession()

 
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-white min-h-[125vh]`}
      >
        <Header user={user} categorySelector={<HeaderCategorySelector  />}  />
        {children}
        <Script src="https://cloud.umami.is/script.js"  data-website-id="77f50e66-39de-4a54-952f-2de40dc464aa" strategy="beforeInteractive" />
        <Suspense>
          <AnalyticsTracker user={user} />
        </Suspense>
        <Cart />
        <SanityLive/>
      </body>
    </html>
  );
}

export default RootLayout